spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.226.100
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xxx.bean
  mapper-locations:
    - mappers/*.xml
logging:
  level:
    com.xxx.mapper: debug
