server:
  port: 18082

spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true